name: test

on:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby:
          - jruby
          - 2.2
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 2.8
          - 2.9
          - 3.0
          - 3.1
          - 3.2
          - 3.3
          - 3.4
    steps:
      - uses: actions/checkout@v4
#      - run: curl -sSL https://get.rvm.io | bash
#      - run: source /home/runner/.rvm/scripts/rvm && rvm install ${{ matrix.ruby }}
#      - run: sudo apt-add-repository -y ppa:rael-gc/rvm
#      - run: sudo apt-get update
#      - run: sudo apt-get install rvm
#      - run: sudo usermod -a -G rvm $USER

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install

      - run: bin/tf_test test/*/*.rb && bundle exec tf --text test/comment/*_comment_test.sh

  all-passed:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - tests
    steps:
      - run: exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
